name: yhschool
description: Art application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.2+27

environment:
  sdk: ">=2.7.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dio: ^4.0.0
  shared_preferences: ^2.0.5
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  pull_to_refresh: ^2.0.0
  loadmore: ^2.0.1
  permission_handler: ^8.1.1
  json_serializable: ^4.1.2
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  fluttertoast: ^8.0.7
  video_player: ^2.1.1
  chewie: ^1.0.0  #video_player播放空间
  audioplayers: ^0.20.1 # music播放
  flutter_staggered_grid_view: ^0.4.0 # 瀑布流
  photo_view: ^0.13.0
  cached_network_image: ^3.0.0
  webview_flutter: ^2.0.9  # webview网页插件
  flutter_html: ^2.2.1
  #webview_flutter_plus: ^0.2.2
  flutter_webview_plugin: ^0.4.0
  multi_image_picker: ^4.8.1 # 多张图选择
  http_parser: ^4.0.0
  #loading_indicator_view: ^1.1.0 # loading动画
  flutter_image_compress: ^1.1.0  #图片压缩
  path_provider: ^2.0.2  #图片保存
  device_info: ^2.0.2  # 取当前设备的系统信息
  flutter_native_image: ^0.0.6 #图片压缩
  flutter_absolute_path: ^1.0.6 #读取本地图片
  date_format: ^2.0.2 # 日期格式转换
  flutter_easyloading: ^3.0.0 #loading效果
  package_info: ^2.0.2 # 获取应用信息
  open_appstore: ^1.0.2 # 打开appstore下载页面
  url_launcher: ^6.0.9  # 打开本地浏览器
  sqflite: ^2.0.0+4    # 本地数据库
  wakelock: ^0.5.6   #  屏幕常亮
  get_it: ^7.2.0   # 拨打电话相关
  image_gallery_saver: ^1.7.1 # 保存图片到本地
  image_cropper: ^1.4.1  # 图片剪切
  # intl: ^0.17.0  # 日期格式转换 包含获取星期
  table_calendar: ^3.0.3
  image_picker: ^0.8.4+3 # 本地图片视频选择
  #flutter_ffmpeg: ^0.4.2  # 视频压缩插件
  dio_cache_interceptor: ^3.0.2 # 缓存拦截器
  animated_text_kit: ^4.2.1 # 文本动画
  flutter_datetime_picker: ^1.5.1 # 日期选择器
  #qr_flutter: ^4.0.0 #二维码
  barcode_scan2: ^4.1.4 #二维码
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - image/ic_arrow_right.png
    - image/ic_arrow_left.png
    - image/ic_folders.png
    - image/ic_imgs.png
    - image/ic_add.png
    - image/ic_more.png
    - image/ic_delete.png
    - image/ic_more_btn.png
    - image/ic_shared_more.png
    - image/ic_shared.png
    - image/ic_plus.png
    - image/ic_fork.png
    - image/ic_nodata.png
    - image/ic_editor.png
    - image/ic_push.png
    - image/ic_gallery.png
    - image/ic_collect_normal.png
    - image/ic_collect_select.png
    - image/ic_play.png
    - image/ic_play_30.png
    - image/ic_round_close.png
    - image/ic_video_add.png
    - image/ic_video_select.png
    - image/ic_normal.png
    - image/ic_head.png
    - image/ic_mine_version.png
    - image/ic_mine_material.png
    - image/ic_mine_collect.png
    - image/ic_mine_phone.png
    - image/ic_mine_subject.png
    - image/ic_tab_video_select.png
    - image/ic_tab_video_normal.png
    - image/ic_tab_gallery_select.png
    - image/ic_tab_gallery_normal.png
    - image/ic_tab_class_select.png
    - image/ic_tab_class_normal.png
    - image/ic_tab_mine_select.png
    - image/ic_tab_mine_normal.png
    - image/ic_tab_zl_select.png
    - image/ic_tab_zl_normal.png
    - image/ic_return.png
    - image/ic_tab_more.png
    - image/ic_advert1.png
    - image/ic_advert2.png
    - image/ic_advert3.png
    - image/ic_refresh.png
    - image/ic_brochure.png
    - image/ic_eg_word.png
    - image/ic_setting.png
    - image/ic_column.png
    - image/ic_wordgroup.png
    - image/ic_word.png
    - image/ic_mywork.png
    - image/ic_myteacher.png
    - image/ic_mycollect.png
    - image/ic_mycourse.png
    - image/ic_mv.png
    - image/ic_music.png
    - image/ic_advise.png
    - image/ic_about_yihua.png
    - image/ic_btn_plan.png
    - image/ic_btn_editor.png
    - image/ic_tips.png
    - image/ic_more_column.png
    - image/start.png
    - image/ic_tool_add.png
    - image/ic_tool_photo.png
    - image/ic_tool_collect.png
    - image/ic_tool_plan.png
    - image/ic_tool_editor_plan.png
    - image/ic_tool_add_normal.png
    - image/ic_tool_add_select.png
    - image/ic_tool_work.png
    - image/ic_logo.png
    - image/ic_live.png
    - image/ic_btn_work.png
    - image/ic_btn_plan.png
    - image/ic_btn_push.png
    - image/ic_live_delete.png
    - image/ic_live_qr.png
    - image/ic_live_editor.png
    - image/ic_live_date.png
    - image/ic_living.png
    - image/ic_live_end.png
    - image/ic_qr.png
    - image/ic_about.png
    - image/ic_mark.png
    - image/ic_active.png
    - image/ic_red_refresh.png
    - image/ic_score.png
    - image/ic_correct.png
    - image/ic_login_bg.png
    - image/ic_school.png
    - image/ic_comment.png
    - image/ic_work_mark.png
    - videos/login_page.mp4
    - videos/x2/login_page_x2.mp4
    - videos/x2/login_page_android_x2.mp4
    - files/player_ios.html
    - files/about.html
    - files/treaty.html
    - data/user.json
    - data/help.json
    - files/audio/audio_player.html
